export default defineAppConfig({
  ui: {
    colors: {
      primary: 'sky',
    },
    icons: {
      arrowDown: 'i-hugeicons-arrow-down-02',
      arrowLeft: 'i-hugeicons-arrow-left-02',
      arrowRight: 'i-hugeicons-arrow-right-02',
      arrowUp: 'i-hugeicons-arrow-up-02',
      caution: 'i-hugeicons-alert-square',
      check: 'i-hugeicons-tick-01',
      chevronDoubleLeft: 'i-hugeicons-arrow-left-double',
      chevronDoubleRight: 'i-hugeicons-arrow-right-double',
      chevronDown: 'i-hugeicons-arrow-down-01',
      chevronLeft: 'i-hugeicons-arrow-left-01',
      chevronRight: 'i-hugeicons-arrow-right-01',
      chevronUp: 'i-hugeicons-arrow-up-01',
      close: 'i-hugeicons-cancel-01',
      copy: 'i-hugeicons-copy-01',
      copyCheck: 'i-hugeicons-checkmark-square-03',
      dark: 'i-hugeicons-moon',
      drag: 'i-hugeicons-drag-drop-vertical',
      ellipsis: 'i-hugeicons-more-horizontal',
      error: 'i-hugeicons-alert-diamond',
      external: 'i-hugeicons-square-arrow-up-right',
      eye: 'i-hugeicons-view',
      eyeOff: 'i-hugeicons-view-off',
      file: 'i-hugeicons-file-01',
      folder: 'i-hugeicons-folder-01',
      folderOpen: 'i-hugeicons-folder-02',
      hash: 'i-lucide-hash',
      info: 'i-hugeicons-information-square',
      light: 'i-hugeicons-sun-01',
      loading: 'i-hugeicons-loading-01',
      menu: 'i-hugeicons-menu-10',
      minus: 'i-hugeicons-minus-sign',
      panelClose: 'i-hugeicons-pointing-left-03',
      panelOpen: 'i-hugeicons-pointing-right-03',
      plus: 'i-hugeicons-plus-sign',
      reload: 'i-hugeicons-reload',
      search: 'i-hugeicons-search-01',
      stop: 'i-hugeicons-stop',
      success: 'i-hugeicons-checkmark-square-01',
      system: 'i-hugeicons-computer',
      tip: 'i-hugeicons-idea',
      upload: 'i-hugeicons-upload-02',
      warning: 'i-hugeicons-alert-02',
    },
  },
})
